sudo: false
language: python
python:
- '3.6'
services:
- memcached
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install coveralls
script:
- pycodestyle memcached_clients/
- coverage run memcached_clients/test.py -v
after_script:
- coveralls
