sudo: false
language: python
python:
- '3.6'
services:
- memcached
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install coveralls
script:
- pycodestyle memcached_clients/
- LIVE_TESTS=1 coverage run memcached_clients/test.py -v
after_script:
- coveralls
before_deploy:
- find memcached_clients/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > memcached_clients/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: ldjWGVmrq0jrQRRRt0l6gbnX/qYHY9dOqwBdJACgGJ1GBOW3TkD1wnMbl8oSayAdhBChEla8og3XpcPoXf+6gg+3hXbcEkOnClE0LPELdXNqZEg6CLQ54qhY+MAw+FhcxdoiFfsnA+aQeRuhjc+OoVqUzE8AmiTWuZz2tj6R0Gbo+9XgR3/qb6T74RZU8KP4rgw1Siy7TOJtl+UN89Q9BOnswj790U6bCBNge2jpKqemA+QzUzYeensUQe4lNJGTuytJSddNq53xTKW2qLFMt0JA2eSMzgm4ZXKiQ1/DbaRyTUlSxGAPTS5wcKahe5UGUiDwW+kX5QNBCeC9vkKdw7wjtWndbST76BBKf0c7BUYNaAQmt0sjRg31w2M/QfrE0vMf1pCuxRqLp75t122ZdPVqxWyMiSosDMdBeDOL/ev++LTcJhDpX6DVGpORHqbgpv4YsghKOOPSO3V+C6CPpuP8/50wL/VNcrJ7d+M6N/h69cuhFQ/Olg/0p6/tVUCmpVobpmqOU9n2/I11pM9G2HSfjLSWxKTKzb85AdMdCD4uqxoDGsUoMNC8kedFvkA1e00JHOTFWzoZOyiap20Y3a+mawcDLpRkQwqL+8mdm2lldQOfuzvCVQHb4Ct/lDExW36OVIgkHmi2+BkZM6EgYGY/g+CXR1Y+gLUT0B1e3c8=
  on:
    tags: true
    python: '3.6'
