sudo: false
language: python
python:
- '3.6'
services:
- memcached
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install coveralls
script:
- pycodestyle memcached_clients/
- LIVE_TESTS=1 coverage run memcached_clients/test.py -v
after_script:
- coveralls
before_deploy:
- find memcached_clients/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > memcached_clients/VERSION
deploy:
  provider:
  user:
  skip_cleanup: true
  password:
  on:
    tags: true
    python: '3.6'
